"""empty message

Revision ID: 154e01e1131d
Revises: 
Create Date: 2023-11-04 00:56:16.781946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154e01e1131d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barangay_official',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('sex', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('birthdate', sa.String(length=50), nullable=True),
    sa.Column('relocation_year', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=True),
    sa.Column('item_quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resident',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('sex', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('birthdate', sa.String(length=50), nullable=True),
    sa.Column('relocation_year', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('countryside_court_reservation_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('number_of_attendees', sa.Integer(), nullable=True),
    sa.Column('reservation_date', sa.String(length=255), nullable=True),
    sa.Column('reservation_time', sa.String(length=255), nullable=True),
    sa.Column('resident_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['resident_id'], ['resident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_rentals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resident_id', sa.String(length=255), nullable=False),
    sa.Column('chairs_borrowed', sa.Integer(), nullable=True),
    sa.Column('tables_borrowed', sa.Integer(), nullable=True),
    sa.Column('tents_borrowed', sa.Integer(), nullable=True),
    sa.Column('borrow_date', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['resident_id'], ['resident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maligaya_court_reservation_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('number_of_attendees', sa.Integer(), nullable=True),
    sa.Column('reservation_date', sa.String(length=255), nullable=True),
    sa.Column('reservation_time', sa.String(length=255), nullable=True),
    sa.Column('resident_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['resident_id'], ['resident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tennis_court_reservation_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('number_of_attendees', sa.Integer(), nullable=True),
    sa.Column('reservation_date', sa.String(length=255), nullable=True),
    sa.Column('reservation_time', sa.String(length=255), nullable=True),
    sa.Column('resident_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['resident_id'], ['resident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tennis_court_reservation_list')
    op.drop_table('maligaya_court_reservation_list')
    op.drop_table('item_rentals')
    op.drop_table('countryside_court_reservation_list')
    op.drop_table('resident')
    op.drop_table('items')
    op.drop_table('barangay_official')
    # ### end Alembic commands ###
