"""empty message

Revision ID: 3ac56c293000
Revises: 271c25817c90
Create Date: 2023-08-02 18:31:12.125867

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ac56c293000'
down_revision = '271c25817c90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barangay_official', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.drop_column('role')

    with op.batch_alter_table('resident', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resident', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('barangay_official', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
