"""empty message

Revision ID: 40ef00d6cf72
Revises: 
Create Date: 2023-11-03 17:19:30.824099

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '40ef00d6cf72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo')
    with op.batch_alter_table('barangay_official', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=255), nullable=True))
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_constraint('barangay_official_ibfk_1', type_='foreignkey')
        batch_op.drop_column('photo')

    with op.batch_alter_table('countryside_court_reservation_list', schema=None) as batch_op:
        batch_op.alter_column('resident_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('item_rentals', schema=None) as batch_op:
        batch_op.alter_column('chairs_borrowed',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('tables_borrowed',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('tents_borrowed',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('borrow_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=255),
               nullable=True)

    with op.batch_alter_table('maligaya_court_reservation_list', schema=None) as batch_op:
        batch_op.alter_column('resident_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('resident', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=255), nullable=True))
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_constraint('resident_ibfk_1', type_='foreignkey')
        batch_op.drop_column('photo')

    with op.batch_alter_table('tennis_court_reservation_list', schema=None) as batch_op:
        batch_op.alter_column('resident_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tennis_court_reservation_list', schema=None) as batch_op:
        batch_op.alter_column('resident_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('resident', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('resident_ibfk_1', 'photo', ['photo'], ['id'])
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('role')

    with op.batch_alter_table('maligaya_court_reservation_list', schema=None) as batch_op:
        batch_op.alter_column('resident_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('item_rentals', schema=None) as batch_op:
        batch_op.alter_column('borrow_date',
               existing_type=sa.String(length=255),
               type_=sa.DATE(),
               nullable=False)
        batch_op.alter_column('tents_borrowed',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('tables_borrowed',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('chairs_borrowed',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('countryside_court_reservation_list', schema=None) as batch_op:
        batch_op.alter_column('resident_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('barangay_official', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('barangay_official_ibfk_1', 'photo', ['photo'], ['id'])
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('role')

    op.create_table('photo',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('file_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('data', mysql.LONGBLOB(), nullable=False),
    sa.Column('owner_id', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['resident.id'], name='photo_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
