"""empty message

Revision ID: 5e2dc1611d71
Revises: 8af093a52e3d
Create Date: 2023-11-03 22:45:27.680605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e2dc1611d71'
down_revision = '8af093a52e3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barangay_official', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.BLOB(),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('resident', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.BLOB(),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resident', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.BLOB(),
               existing_nullable=True)

    with op.batch_alter_table('barangay_official', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
