"""empty message

Revision ID: 6b561a1ed9f1
Revises: e985cae03572
Create Date: 2023-08-02 18:38:34.763561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b561a1ed9f1'
down_revision = 'e985cae03572'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resident', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barangay_number', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('sex', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('birthdate', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('relocation_year', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resident', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('relocation_year')
        batch_op.drop_column('birthdate')
        batch_op.drop_column('sex')
        batch_op.drop_column('barangay_number')

    # ### end Alembic commands ###
