"""empty message

Revision ID: 6b760b8c8bdb
Revises: ef22ba41872e
Create Date: 2023-08-02 20:43:48.108732

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6b760b8c8bdb'
down_revision = 'ef22ba41872e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resident', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.BLOB(), nullable=False))
        batch_op.add_column(sa.Column('full_name', sa.String(length=255), nullable=False))
        batch_op.alter_column('barangay_number',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resident', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('barangay_number',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('full_name')
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
