"""empty message

Revision ID: e985cae03572
Revises: 3ac56c293000
Create Date: 2023-08-02 18:32:01.522051

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e985cae03572'
down_revision = '3ac56c293000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resident', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resident', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', mysql.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
