"""empty message

Revision ID: ef22ba41872e
Revises: c5acaaaaf2d2
Create Date: 2023-08-02 19:57:22.514215

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef22ba41872e'
down_revision = 'c5acaaaaf2d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resident', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.String(length=255), nullable=False))
        batch_op.drop_column('UUIDv4')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resident', schema=None) as batch_op:
        batch_op.add_column(sa.Column('UUIDv4', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###
